# Filename: p2.py
# Author: Michael Bell
# Date Created: 09/24/2022
# Date Last Modified: 09/24/2022
# Email: msb5390@gmail.com

# From ProjectEuler.net
# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. Starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

n0 = 1
n1 = 2
even_sum = n1

while n0 + n1 <= 4E6:
    n0, n1 = n1, n0 + n1
    if not n1 % 2:
        even_sum += n1

print('The sum of the even-valued terms of the Fibonacci sequence',
      'whose values do not exceed four million is:')
print(even_sum)
